# Generated by Django 4.0.3 on 2022-06-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customer_address_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerSliderItem', models.ImageField(upload_to='BannerImg')),
            ],
        ),
    ]
