# Generated by Django 4.0.3 on 2022-06-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bannerslider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerslider',
            old_name='bannerSliderItem',
            new_name='banner_slider_item',
        ),
    ]
